"""Build compact Latin font faces while retaining original extended-glyph fallbacks.

Offline build tool: Python 3 + fonttools[woff] 4.65.0. No runtime dependency.
Run from the repository root: python scripts/prepare-fonts.py
"""
from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.pens.recordingPen import RecordingPen

ROOT = Path(__file__).resolve().parents[1]
# Common Latin text and punctuation; the original faces cover every other glyph.
RANGES = [(0x0, 0xFF), (0x2000, 0x206F), (0x2190, 0x2199)]
EXTRA = {0x131, 0x152, 0x153, 0x20AC, 0x2122, 0x2212, 0xFEFF, 0xFFFD}
LATIN = {code for start, end in RANGES for code in range(start, end + 1)} | EXTRA
LATIN_CSS = "U+0000-00FF,U+0131,U+0152-0153,U+2000-206F,U+20AC,U+2122,U+2190-2199,U+2212,U+FEFF,U+FFFD"


def compact_ranges(points):
    runs = []
    for point in sorted(points):
        if runs and runs[-1][1] + 1 == point:
            runs[-1][1] = point
        else:
            runs.append([point, point])
    return ",".join(f"U+{start:04X}" if start == end else f"U+{start:04X}-{end:04X}" for start, end in runs)


faces = []
for name, family, weight in [
    ("Geist-Regular", "Shruggie Geist", 400),
    ("Geist-Medium", "Shruggie Geist", 500),
    ("GeistMono-Regular", "Shruggie Geist Mono", 400),
]:
    source = ROOT / "public/fonts" / f"{name}.woff2"
    original = TTFont(source)
    font = TTFont(source, recalcTimestamp=False)
    options = subset.Options()
    options.name_IDs = ["*"]
    options.name_languages = ["*"]
    options.layout_features = ["*"]
    options.glyph_names = True
    options.notdef_outline = True
    options.passthrough_tables = True
    worker = subset.Subsetter(options=options)
    worker.populate(unicodes=LATIN)
    worker.subset(font)
    target = source.with_name(f"{name}-Latin.woff2")
    font.save(target)
    optimized = TTFont(target)
    original_glyphs = original.getGlyphSet()
    optimized_glyphs = optimized.getGlyphSet()
    for code, glyph in optimized.getBestCmap().items():
        assert original.getBestCmap()[code] == glyph
    for glyph in optimized.getGlyphOrder():
        assert original["hmtx"][glyph] == optimized["hmtx"][glyph]
        before, after = RecordingPen(), RecordingPen()
        original_glyphs[glyph].draw(before)
        optimized_glyphs[glyph].draw(after)
        assert before.value == after.value, (name, glyph)
        before_program = getattr(original["glyf"][glyph], "program", None)
        after_program = getattr(optimized["glyf"][glyph], "program", None)
        assert (before_program.getBytecode() if before_program else b"") == (after_program.getBytecode() if after_program else b"")
    for table, attributes in [("head", ["unitsPerEm"]), ("hhea", ["ascent", "descent", "lineGap"]), ("OS/2", ["sTypoAscender", "sTypoDescender", "sTypoLineGap", "usWinAscent", "usWinDescent"])]:
        for attribute in attributes:
            assert getattr(original[table], attribute) == getattr(optimized[table], attribute)
    extended = set(original.getBestCmap()) - LATIN
    assert not extended.intersection(optimized.getBestCmap())
    assert extended | set(optimized.getBestCmap()) == set(original.getBestCmap())
    faces.append(f'@font-face {{\n  font-family: "{family}";\n  src: url("/fonts/{name}.woff2") format("woff2");\n  font-style: normal;\n  font-weight: {weight};\n  font-display: swap;\n  unicode-range: {compact_ranges(extended)};\n}}')
    print(f"{name}: {source.stat().st_size} -> {target.stat().st_size} bytes; {len(optimized.getBestCmap())} glyphs verified, {len(extended)} supplied by original")
css = "/* Generated by scripts/prepare-fonts.py; original glyph coverage stays available. */\n\n" + "\n\n".join(faces) + "\n"
(ROOT / "styles/font-extended.css").write_text(css, encoding="utf-8", newline="\n")
print("Latin unicode range:", LATIN_CSS)
